### ISSUE TITLE
what about model

### ISSUE THREAD

**Issue by nine-2-five** [dciccale/requirejs-underscore-tpl#7]
I'm having trouble with reading model data I pass to ItemView that uses this templating plugin:

```
define(["app", "models/user", "tpl!html/login.html"], function (IzazovCard, User, TplLogin) {
    console.log("login");
    var user = new User();
    var LoginPage = Marionette.ItemView.extend({
        template: TplLogin,
        model: user,

        onShow: function(){
            // react to when a view has been shown
            console.log(this.model);
        }
    });

    return LoginPage;
});
```

**Comment by dciccale** [comment]
hi, thanks for opening an issue.

what kind of trouble do you have? could you be more specific?

thx

**Comment by nine-2-five** [comment]
I'm sorry for taking your time it seems it was my lack of understanding how backbone models are initialized. Once I initialized it properly everything turned out ok with your plugin.
